[build]
  # 1. Netlify runs this command to compile your React code
  command = "npm run build"
  # 2. Netlify publishes the contents of this folder (your React output)
  publish = "build"
  # 3. Netlify looks here for your serverless functions
  functions = "netlify/functions"

[[redirects]]
  # This rule is essential for Single Page Applications (SPAs) like React.
  # It ensures that deep links (like /analysis) are served by index.html.
  from = "/*"
  to = "/index.html"
  status = 200